# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "openstack" do |openstack|

    openstack.vm.box = "ubuntu18"
    openstack.disksize.size = "120GB"
    openstack.vm.network "private_network", ip: "192.168.137.130"
    openstack.vm.hostname="ubuntu18"

    openstack.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    openstack.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu18"
      vb.cpus = "4"
      vb.memory = "4096"
  end

  openstack.vm.provision "shell", :path => "shell.sh"
end
end
