# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  
  config.vm.define "master" do |master|

  master.vm.box = "Centos7.6"
  master.disksize.size = "120GB"
  master.vm.network "private_network", ip: "192.168.137.100"
  master.vm.hostname="master"

  master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = "3072"
      vb.cpus = "2"
  end

  master.vm.provision "shell", :path => "master.sh"
  end

  (1..2).each do |i|
    config.vm.define "node#{i}" do |node|

    node.vm.box = "Centos7.6"
    node.disksize.size = "120GB"

    node.vm.network "private_network", ip: "192.168.137.10#{i}"
    node.vm.hostname="node#{i}"
    node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i}"
        vb.memory = "3072"
        vb.cpus = "2"
      end
     
      node.vm.provision "shell", :path => "node.sh"
      end
    end
end
