# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  
  config.vm.define "kubemaster" do |kubemaster|

  kubemaster.vm.box = "Centos7.6"
  kubemaster.disksize.size = "120GB"
  kubemaster.vm.network "private_network", ip: "192.168.137.100"
  kubemaster.vm.hostname="kubemaster"

  kubemaster.vm.provider "virtualbox" do |vb|
      vb.name = "kubemaster"
      vb.memory = "3072"
      vb.cpus = "2"
  end

  kubemaster.vm.provision "shell", :path => "master.sh"
  end

  (1..2).each do |i|
    config.vm.define "kube#{i}" do |kube|

    kube.vm.box = "Centos7.6"
    kube.disksize.size = "120GB"

    kube.vm.network "private_network", ip: "192.168.137.10#{i}"
    kube.vm.hostname="kube#{i}"
    kube.vm.provider "virtualbox" do |vb|
        vb.name = "kube#{i}"
        vb.memory = "3072"
        vb.cpus = "2"
      end
     
      kube.vm.provision "shell", :path => "node.sh"
      end
    end
end
